version: '3'
services:
    django:
        ports:
            - "8000:8000" 
        volumes:
            - ./youtube:/code
        build:
            context: ./youtube
            dockerfile: Dockerfile.django

